import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Argo Energy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-Ranade">
        <Header />
        <Hero />
        <footer className="bg-black py-8 text-center text-sm text-gray-200 lg:hidden">
          © {new Date().getFullYear()} Copy Interactive, All Rights Reserved
        </footer>
      </main>
    </div>
  );
}
